name: 'Docker Build and Push Action (Bash)'

description: 'A GitHub Action to build and push Docker images'

inputs:
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub password or token'
    required: true
    secret: true
  image_name:
    description: 'The Docker image name to build and push'
    required: true
  tags:
    description: 'Comma-separated tags for the Docker image'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - run: |
        echo "Running inline script"
        cd workflow
        pwd
        ls -ltr
        if [ -f "/harness/workflow/composite-0.sh" ]; then
        echo "composite-0.sh exists, displaying contents:"
        cat /harness/workflow/composite-0.sh

        # Check if composite-1.sh exists
        elif [ -f "/harness/workflow/composite-1.sh" ]; then
        echo "composite-1.sh exists, displaying contents:"
        cat /harness/workflow/composite-1.sh

        # If neither file exists
        else
        echo "Neither composite-0.sh nor composite-1.sh exists."
        fi
      shell: bash

    - run: |
        /harness/workflow/main.sh
      shell: bash
      working-directory: .
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        image_name: ${{ inputs.image_name }}
        tags: ${{ inputs.tags }}
